//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolCribData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeneralTablesEntities : DbContext
    {
        public GeneralTablesEntities()
            : base("name=GeneralTablesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TranDetail> TranDetails { get; set; }
        public DbSet<Transactions_Not_Entered> Transactions_Not_Entered { get; set; }
        public DbSet<Manual_Entry_Transactions> Manual_Entry_Transactions { get; set; }
    }
}
