//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolCribData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manual_Entry_Transactions
    {
        public string Date { get; set; }
        public string Qty { get; set; }
        public string PartNumber { get; set; }
        public string CoronaPartID { get; set; }
        public string Description { get; set; }
        public string EmpID { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public Nullable<bool> MasonUpdated { get; set; }
        public int TranID { get; set; }
        public System.Guid TranDetailID { get; set; }
        public string Comment { get; set; }
    }
}
