//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolCribData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDetail
    {
        public Nullable<int> TranID { get; set; }
        public string PartID { get; set; }
        public string Qty { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> MasonUpdated { get; set; }
        public System.Guid TranDetailID { get; set; }
    }
}
